import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { gunzipSync } from 'node:zlib';
const files=readdirSync('source_parts').filter(n=>/^App\.gz\.b64\.part\d+\.txt$/.test(n)).sort();
if(files.length!==8) throw new Error(`Expected 8 compressed App source parts, found ${files.length}`);
let source=gunzipSync(Buffer.from(files.map(n=>readFileSync(`source_parts/${n}`,'utf8').trim()).join(''),'base64')).toString('utf8');
const rich="variants: variants.sort((a,b)=>a.sort_order-b.sort_order).map(v=>({id:v.id,name:v.name,price:Number(v.price ?? p.price),stock:v.stock}))";
if(source.includes(rich)) source=source.replace(rich,"variants: variants.sort((a,b)=>a.sort_order-b.sort_order).map(v=>v.name).filter(Boolean)");
source=source.replace("const [selectedQty, setSelectedQty] = useState(1);","const [selectedQty, setSelectedQty] = useState(1);\n  const [activeProductImage, setActiveProductImage] = useState('');\n  const [lightboxImage, setLightboxImage] = useState('');");
source=source.replace("setSelectedQty(1);\n    setBuyerPage('product');","setSelectedQty(1);\n    setActiveProductImage((product.images && product.images[0]) || product.image || '');\n    setBuyerPage('product');");
source=source.replace(/setEditingProduct\(\{ id: null, name: '', category: 'Phụ Kiện Điện Thoại', price: '', originalPrice: '', stock: '', image: '', variants: '', description: '' \}\);/,"setEditingProduct({ id: null, name: '', category: 'Phụ Kiện Điện Thoại', price: '', originalPrice: '', stock: '', image: '', images: [], variants: '', description: '' });");
source=source.replace("setEditingProduct({ ...p, variants: p.variants.join(', ') });","setEditingProduct({ ...p, images: (p.images?.length ? p.images : (p.image ? [p.image] : [])), variants: p.variants.join(', ') });");
source=source.replace(/const handleImageFile = \(e\) => \{[\s\S]*?\n  \};\n  const saveProduct = \(\) => \{/,`const handleImageFile = (e) => {
    const files:any[] = Array.from(e.target.files || []); if(!files.length)return;
    if(files.some((f:any)=>f.size>2*1024*1024)){showToast('Mỗi ảnh tối đa 2MB');e.target.value='';return;}
    const current=editingProduct?.images || (editingProduct?.image?[editingProduct.image]:[]); const picked=files.slice(0,Math.max(0,9-current.length));
    if(!picked.length){showToast('Mỗi sản phẩm tối đa 9 ảnh');e.target.value='';return;}
    Promise.all(picked.map((f:any)=>new Promise(resolve=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.readAsDataURL(f)}))).then((added:any[])=>setEditingProduct((prev:any)=>{const images=[...(prev.images||(prev.image?[prev.image]:[])),...added].slice(0,9);return {...prev,images,image:images[0]||''}})); e.target.value='';
  };
  const saveProduct = () => {`);
source=source.replace(/stock: Number\(editingProduct\.stock\) \|\| 0, image: editingProduct\.image \|\| p\.image,/,"stock: Number(editingProduct.stock) || 0, image: editingProduct.images?.[0] || editingProduct.image || p.image, images: editingProduct.images?.length ? editingProduct.images : (editingProduct.image ? [editingProduct.image] : (p.images || [p.image])),");
source=source.replace(/image: editingProduct\.image \|\| 'https:\/\/images\.unsplash\.com\/photo-1526406915894-7bcd65f60845\?w=600&q=80',/,"image: editingProduct.images?.[0] || editingProduct.image || 'https://images.unsplash.com/photo-1526406915894-7bcd65f60845?w=600&q=80', images: editingProduct.images?.length ? editingProduct.images : (editingProduct.image ? [editingProduct.image] : []),");
source=source.replace(/<input ref=\{fileInputRef\} type="file" accept="image\/png,image\/jpeg" onChange=\{handleImageFile\} className="hidden" \/>/g,'<input ref={fileInputRef} type="file" multiple accept="image/png,image/jpeg,image/webp" onChange={handleImageFile} className="hidden" />');
const ep=source.indexOf('<div className="flex items-start gap-3">',source.indexOf('Hình ảnh sản phẩm'));
if(ep!==-1){const ui=`<div className="mb-3 flex flex-wrap gap-2">{(editingProduct.images||(editingProduct.image?[editingProduct.image]:[])).map((img,idx)=><div key={idx} className="relative w-20 h-20 rounded-lg overflow-hidden border-2 border-gray-100"><img src={img} className="w-full h-full object-cover" />{idx===0&&<span className="absolute bottom-0 inset-x-0 bg-[#EE4D2D] text-white text-[8px] text-center">Đại diện</span>}<button type="button" onClick={()=>setEditingProduct((prev:any)=>{const images=(prev.images||[prev.image]).filter((_,i)=>i!==idx);return {...prev,images,image:images[0]||''}})} className="absolute top-1 right-1 bg-black/60 text-white rounded-full p-0.5"><X size={9}/></button>{idx>0&&<button type="button" onClick={()=>setEditingProduct((prev:any)=>{const images=[...(prev.images||[prev.image])];[images[idx-1],images[idx]]=[images[idx],images[idx-1]];return {...prev,images,image:images[0]}})} className="absolute top-1 left-1 bg-white/90 rounded px-1 text-[9px]">←</button>}</div>)}{(editingProduct.images||(editingProduct.image?[editingProduct.image]:[])).length<9&&<button type="button" onClick={()=>fileInputRef.current?.click()} className="w-20 h-20 border-2 border-dashed border-gray-300 rounded-lg flex flex-col items-center justify-center text-gray-400"><ImagePlus size={18}/><span className="text-[9px]">Thêm ảnh</span></button>}</div>\n                      `;source=source.slice(0,ep)+ui+source.slice(ep);console.log('Injected multi-image seller editor')}
const detailStart=source.indexOf('CHI TIẾT SẢN PHẨM');
if(detailStart!==-1){const tail=source.slice(detailStart);const re=/<img([^>]*?)src=\{selectedProduct\.image\}([^>]*?)\/>/;const m=tail.match(re);if(m){const replacement=`<button type="button" onClick={()=>setLightboxImage(activeProductImage||selectedProduct.image)} className="block w-full"><img$1src={activeProductImage||selectedProduct.image}$2/></button>{(selectedProduct.images?.length||0)>1&&<div className="flex gap-2 overflow-x-auto mt-2 pb-1">{selectedProduct.images.map((img,idx)=><button type="button" key={idx} onClick={()=>setActiveProductImage(img)} className={\`w-14 h-14 flex-shrink-0 rounded-lg overflow-hidden border-2 \${(activeProductImage||selectedProduct.image)===img?'border-[#EE4D2D]':'border-gray-100'}\`}><img src={img} className="w-full h-full object-cover" /></button>)}</div>}`;source=source.slice(0,detailStart)+tail.replace(re,replacement);console.log('Injected product image gallery')}else console.warn('Selected product image not found')}
const marker='      {/* HỘP THOẠI XÁC NHẬN */}';if(source.includes(marker))source=source.replace(marker,`{lightboxImage&&<div onClick={()=>setLightboxImage('')} className="fixed inset-0 z-[100] bg-black/90 flex items-center justify-center p-4"><button onClick={()=>setLightboxImage('')} className="absolute top-5 right-5 text-white bg-white/10 rounded-full p-2"><X size={24}/></button><img onClick={e=>e.stopPropagation()} src={lightboxImage} className="max-w-full max-h-[90vh] object-contain rounded-lg" /></div>}\n\n${marker}`);
writeFileSync('src/App.tsx',source);console.log(`Assembled src/App.tsx from ${files.length} compressed source parts (${source.length} chars).`);
