name: Export source
on:
  push:
    paths:
      - '.github/workflows/export-source.yml'
jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/upload-artifact@v4
        with:
          name: kimshop-full-source
          path: .
          retention-days: 1
